"""baseline schema

Revision ID: ad26fa64a48a
Revises: 
Create Date: 2026-09-17 17:38:03.985953
"""
from alembic import op
import sqlalchemy as sa


revision = 'ad26fa64a48a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
